#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\portal.bof
BOFS = hellport.bof corpport.bof necport.bof corpnode.bof \
       museumport.bof ghallport.bof


!include $(KODDIR)\kod.mak
