#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\wanderer.bof
BOFS  =  jgeneral.bof minstrel.bof heretic.bof dkwizard.bof huntghst.bof \
         izzio.bof harbinger.bof joline.bof

!include $(KODDIR)\kod.mak
