#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\activeskill.bof
BOFS = cleave.bof unleash.bof sprint.bof mark.bof dash.bof backstab.bof

!include $(KODDIR)\kod.mak
