#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\weapon.bof
BOFS = shrtswrd.bof mystswrd.bof mace.bof bkdagger.bof spirhamm.bof\
        scimitar.bof longswrd.bof hammer.bof ranged.bof axe.bof goldswrd.bof \
        riijaswd.bof neruswd.bof huntsw.bof unique.bof testswrd.bof \
        thrownweapon.bof maul.bof club.bof iceswrd.bof knife.bof kukri.bof \
        machete.bof hatchet.bof mallet.bof lightswrd.bof fireswrd.bof \
        blackaxe.bof blackhammer.bof silvance.bof dagger.bof

!include $(KODDIR)\kod.mak
