#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\interactive.bof
BOFS = cookpot.bof plantsoil.bof guilddevice.bof forge.bof psychostatue.bof \
       swordrock.bof

!include $(KODDIR)\kod.mak
