#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bergtwn.bof
BOFS  = bergvaultm.bof berginnk.bof bergmerch.bof bergsmithm.bof bergbanker.bof bergaucm.bof

!include $(KODDIR)\kod.mak
