#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\teleportspell.bof
BOFS = rescue.bof blink.bof elusion.bof deathrift.bof shadrift.bof nodetravel.bof

!include $(KODDIR)\kod.mak
