#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bergrm.bof

BOFS = bergcity.bof bergvault.bof bergsmith.bof berghall.bof bergstore.bof berginn.bof bergbank.bof bergauc.bof

!include $(KODDIR)\kod.mak
