#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\cooldown.bof
BOFS = cooldownnb.bof cooldownsb.bof cooldowncreawings.bof \
       cooldownsprint.bof


!include $(KODDIR)\kod.mak
