#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\emberfused.bof
BOFS = emberheartfused-red.bof emberheartfused-black.bof \
  emberheartfused-blue.bof emberheartfused-brown.bof \
  emberheartfused-green.bof emberheartfused-purple.bof \
  emberheartfused-sky.bof emberheartfused-white.bof \
  emberheartfused-dgreen.bof
!include $(KODDIR)\kod.mak
