#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bow.bof
BOFS = longbow.bof battlbow.bof pracbow.bof magicbow.bof nerubow.bof \
       multibow.bof shortbow.bof huntbow.bof

!include $(KODDIR)\kod.mak
