#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\questtemplate.bof
BOFS = shaldiscqt.bof krandiscqt.bof farendiscqt.bof qordiscqt.bof \
       fadepupilqt.bof dementpupilqt.bof scimprofqt.bof sporepupilqt.bof \
       princessqt.bof dukeloyaltyqt.bof rebelloyaltyqt.bof dukejoinqt.bof \
       rebeljoinqt.bof soldierqt.bof guildshieldqt.bof guildshintroqt.bof \
       luteqt.bof truthspellqt.bof truthendbranchqt.bof bonepriestessqt.bof \
       madscidflyqt.bof tradingpostqt.bof bowmakerqt.bof chickensoupqt.bof \
       stunteddwarfqt.bof hypochondriacqt.bof offeringqt.bof seraphymqt.bof \
       priestessinsigniaqt.bof monkinsigniaqt.bof factioninsigniaqt.bof \
       mysterymobqt.bof moxalscamoneqt.bof moxalscamtwoqt.bof oreqt.bof \
       councilletterqt.bof chessqt.bof loveletterqt.bof spawnlichqt.bof \
       aphrodisiacqt.bof necrowarnevilqt.bof necrowarngoodqt.bof taxqt.bof \
       barrestockqt.bof cateringqt.bof apothecaryqt.bof kocweaponqt.bof \
       kocaleqt.bof warletterqt.bof idpotionqt.bof idwandqt.bof \
       jalanecklaceqt.bof murderqt.bof abstainpvpqt.bof mananodeqt.bof \
       razamumqt.bof ratkingqt.bof nerugolemqt.bof swamphuntqt.bof \
       firegolemqt.bof eastloversqt.bof dangelqt.bof wendigohuntqt.bof \
       bergkingpoliticsqt.bof bergkingspdrqt.bof wolfhuntqt.bof \
       jixainnescort.bof escortassnqt.bof jixabanditqt.bof \
       spinebeastbossqt.bof monstercharmqt.bof resignqt.bof \
       findbergaucqt.bof findjixaqt.bof tosgraveqt.bof marmummiesqt.bof \
       marstatuesqt.bof castlevicqt.bof marentqt.bof fungushuntqt.bof \
       marthrashqt.bof orchuntqt.bof goodfeyhuntqt.bof evfeyhuntqt.bof \
       molluskhuntqt.bof nerutrollhuntqt.bof lupogghuntqt.bof nechuntqt.bof \
       killlichqt.bof bergcryptqt.bof

!include $(KODDIR)\kod.mak
