#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\emberheart.bof
BOFS = emberheart-red.bof emberheart-black.bof \
  emberheart-blue.bof emberheart-brown.bof \
  emberheart-green.bof emberheart-purple.bof \
  emberheart-sky.bof emberheart-white.bof \
  emberheart-dgreen.bof
!include $(KODDIR)\kod.mak
