name: Check File Encoding on Changed Files

on:
  pull_request:  # PR opened, added to, re-opened
    paths:
      - '**.*kod'
      - '**.khd'
      - '**.rc'
jobs:
  check-encoding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List changed files
        id: changed-files
        run: |
          # Fetch the base branch to ensure we have the base commit
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          # List changed files between the base commit and the current commit
          echo "all_changed_files<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check file encoding
        run: |
          FOUND_UTF8=0
          while read -r file; do
            if [[ -n "$file" && -f "$file" ]]; then
              if [[ $(file -i "$file" | grep 'charset=utf-8') ]]; then
                FOUND_UTF8=1
                echo "::error::UTF-8 encoded file found: $file"
              fi
            fi
          done < <(echo "${{ steps.changed-files.outputs.all_changed_files }}")
          if [[ "$FOUND_UTF8" -eq 1 ]]; then
            exit 1
          fi
